/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package OOP_Assignment.GUI;


/**
 *
 * @author Yong Jun
 */
import javax.swing.*;
import java.io.*;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;



public class StaffPage extends javax.swing.JFrame {

    /**
     * Creates new form StaffMenuPage
     */
    public StaffPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        StaffPageText = new javax.swing.JLabel();
        UpdateIndividualLoginAccount = new javax.swing.JButton();
        MakePaymentforResident = new javax.swing.JButton();
        generateReceipt = new javax.swing.JButton();
        AcceptRoomChange = new javax.swing.JButton();
        StaffLogOut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        StaffPageText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        StaffPageText.setText("Staff Page");

        UpdateIndividualLoginAccount.setText("Update Individual Login Account");
        UpdateIndividualLoginAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateIndividualLoginAccountActionPerformed(evt);
            }
        });

        MakePaymentforResident.setText("Make Payment for Resident");
        MakePaymentforResident.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MakePaymentforResidentActionPerformed(evt);
            }
        });

        generateReceipt.setText("Generate Receipt");
        generateReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateReceiptActionPerformed(evt);
            }
        });

        AcceptRoomChange.setText("Accept Resident Room Type Change Request");
        AcceptRoomChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcceptRoomChangeActionPerformed(evt);
            }
        });

        StaffLogOut.setText("Log Out");
        StaffLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StaffLogOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(generateReceipt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(UpdateIndividualLoginAccount, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MakePaymentforResident, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AcceptRoomChange))
                .addGap(24, 24, 24))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(274, 274, 274)
                        .addComponent(StaffLogOut))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(276, 276, 276)
                        .addComponent(StaffPageText)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(StaffPageText)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UpdateIndividualLoginAccount)
                    .addComponent(MakePaymentforResident))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AcceptRoomChange)
                    .addComponent(generateReceipt))
                .addGap(31, 31, 31)
                .addComponent(StaffLogOut)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AcceptRoomChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcceptRoomChangeActionPerformed
        // TODO add your handling code here:
        StaffAcceptResidentRoomTypeChangeRequestPage sa = new StaffAcceptResidentRoomTypeChangeRequestPage();
        sa.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AcceptRoomChangeActionPerformed

    private void generateReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateReceiptActionPerformed
        // TODO add your handling code here:
        StaffGenerateReceiptPage sg = new StaffGenerateReceiptPage();
        sg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_generateReceiptActionPerformed

    private void UpdateIndividualLoginAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateIndividualLoginAccountActionPerformed
        // TODO add your handling code here:
        StaffUpdateIndividualLoginAccountPage su = new StaffUpdateIndividualLoginAccountPage();
        su.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_UpdateIndividualLoginAccountActionPerformed

    private void StaffLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StaffLogOutActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_StaffLogOutActionPerformed

    private void MakePaymentforResidentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MakePaymentforResidentActionPerformed
        // TODO add your handling code here:
        StaffMakePaymentForResidentPage sm = new StaffMakePaymentForResidentPage();
        sm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MakePaymentforResidentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StaffPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StaffPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StaffPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StaffPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StaffPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AcceptRoomChange;
    private javax.swing.JButton MakePaymentforResident;
    private javax.swing.JButton StaffLogOut;
    private javax.swing.JLabel StaffPageText;
    private javax.swing.JButton UpdateIndividualLoginAccount;
    private javax.swing.JButton generateReceipt;
    // End of variables declaration//GEN-END:variables
}
